=== attract-stars/ReqMon/de.fraunhofer.isst.automotive.stars.reqmon.dsl.mapping.ui.test/material/system.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--  targetNamespace="http://www.fraunhofer.de/isst/automotive/stars/reqmon/dsl/mapping/system"
xmlns="http://www.fraunhofer.de/isst/automotive/stars/reqmon/dsl/mapping/system"
elementFormDefault="qualified"> -->


<!-- definition of simple elements -->
<xs:element name="name" type="xs:string"/>
<xs:element name="version" type="xs:string"/>
<xs:element name="description" type="xs:string"/>
<xs:element name="ref" type="xs:integer"/>
<xs:element name="bit_size" type="xs:integer"/>
<xs:element name="location" type="xs:string"/>
<xs:element name="datatype" type="xs:string"/>
<xs:element name="min_value" type="xs:decimal"/>
<xs:element name="max_value" type="xs:decimal"/>
<xs:element name="preferred_value" type="xs:decimal"/>
<xs:element name="step_size" type="xs:decimal"/>
<xs:element name="inheritance_from" type="xs:string"/>

<xs:element name="type">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="class|signal|integer|float|short|double|byte|string|char|time|date|boolean|newType"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<!-- definition of attributes -->
<xs:attribute name="id" type="xs:integer"/>

<!-- definition of complex elements -->
<xs:element name="allocation">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="bit_size"/>
			<xs:element ref="location"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="signal_object">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="ref"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="data_objects">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="signal_object"  maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="message">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="allocation"/>
			<xs:element ref="data_objects"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="signal">
	<xs:complexType>
		<xs:all>
			<xs:element ref="name"/>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="datatype"/>
			<xs:element ref="allocation"/>
			<xs:element ref="min_value"/>
			<xs:element ref="max_value"/>
			<xs:element ref="preferred_value" minOccurs="0"/>
			<xs:element ref="step_size" minOccurs="0"/>
		</xs:all>
		<xs:attribute ref="id"/>
	</xs:complexType>
</xs:element>

<xs:element name="list">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="type" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="set">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="type" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="newType">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="description" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="attrType">
	<xs:complexType>
		<xs:choice>
			<xs:element ref="type"/>
			<xs:element ref="list"/>
			<xs:element ref="set"/>
			<xs:element ref="newType"/>
		</xs:choice>
	</xs:complexType>
</xs:element>

<xs:element name="attribute">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="attrType"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="class">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="inheritance_from" minOccurs="0"/>
			<xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:element name="data_structure">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="allocation"/>
			<xs:element ref="class" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="id"/>
	</xs:complexType>
</xs:element>

<xs:element name="system">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="version" minOccurs="0"/>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="message"/>
			<xs:element ref="signal" maxOccurs="unbounded"/>
			<xs:element ref="data_structure"/>
		</xs:sequence>
		<xs:attribute ref="id"/>
	</xs:complexType>
</xs:element>


</xs:schema>

=== attract-stars/ReqMon/de.fraunhofer.isst.automotive.stars.reqmon.dsl.mapping.ui.test/material/SystemElementExample.xml
<?xml version="1.0" encoding="UTF-8"?>

<system
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="system.xsd"
id='123'>
<!-- xsi:schemaLocation="http://www.fraunhofer.de/isst/automotive/stars/reqmon/dsl/mapping/system system.xsd" -->

	<name></name>
	<version></version>
	<description></description>
	<message>
		<name>MA</name>
		<allocation>
			<bit_size>1024</bit_size>
			<location>X</location>
		</allocation>
		<data_objects>
			<signal_object>
				<ref>1</ref>
			</signal_object>
			<signal_object>
				<ref>2</ref>
			</signal_object>
		</data_objects>
	</message>
	<signal id='1'>
		<name>SA</name>
		<description></description>
		<datatype>SYA</datatype>
		<allocation>
			<bit_size>16</bit_size>
			<location>SX1</location>
		</allocation>
		<min_value>0.0</min_value>
		<max_value>100.0</max_value>
		<preferred_value>50.0</preferred_value>
		<step_size>0.5</step_size>
	</signal>
	<signal id='2'>
		<name>SB</name>
		<datatype>SYB</datatype>
		<allocation>
			<bit_size>8</bit_size>
			<location>SX2</location>
		</allocation>
		<min_value>-1.0</min_value>
		<max_value>1.0</max_value>
		<preferred_value>0.0</preferred_value>
		<step_size>0.1</step_size>
	</signal>
	<data_structure id='1'>
		<name></name>
		<description></description>
		<allocation>
			<bit_size>0</bit_size>
			<location>SX</location>
		</allocation>
		<class> 
			<name>CNA</name>
			<inheritance_from>Parent</inheritance_from>
			<attribute>
				<name>ANA1</name>
				<attrType>
					<type>class</type>
				</attrType>
			</attribute>
			<attribute>
				<name>ANA2</name>
				<attrType>
					<type>signal</type>
				</attrType>
			</attribute>
		</class>
		<class> 
			<name>CNB</name>
			<inheritance_from></inheritance_from>
			<attribute>
				<name>ANB1</name>
				<attrType>
					<type>integer</type>
				</attrType>
			</attribute>
			<attribute>
				<name>ANB2</name>
				<attrType>
					<type>float</type>
				</attrType>
			</attribute>
			<attribute>
				<name>ANB3</name>
				<attrType>
					<type>double</type>
				</attrType>
			</attribute>
		</class>
		<class> 
			<name>CNC</name>
			<inheritance_from></inheritance_from>
			<attribute>
				<name>ANC1</name>
				<attrType>
					<type>short</type>
				</attrType>
			</attribute>
			<attribute>
				<name>ANC2</name>
				<attrType>
					<type>string</type>
				</attrType>
			</attribute>
			<attribute>
				<name>ANC3</name>
				<attrType>
					<type>char</type>
				</attrType>
			</attribute>
			<attribute>
				<name>ANC3</name>
				<attrType>
					<type>byte</type>
				</attrType>
			</attribute>
		</class>
		<class>
			<name>CND</name>
			<attribute>
				<name>AND1</name>
				<attrType>
					<newType>
						<name>newType</name>
					</newType>
				</attrType>
			</attribute>
			<attribute>
				<name>AND2</name>
				<attrType>
					<list>
						<type>string</type>
						<type>char</type>
						<type>boolean</type>
				</list>
				</attrType>
			</attribute>
			<attribute>
				<name>AND2</name>
				<attrType>
					<set>
						<type>integer</type>
					</set>
				</attrType>
			</attribute>
		</class>
	</data_structure>
</system>
